
-- FILENAME:  ./skel/configure_hive_db_lookups.sql
insert into ONT_DB_LOOKUP
(C_DOMAIN_ID, C_PROJECT_PATH, C_OWNER_ID, C_DB_FULLSCHEMA, C_DB_DATASOURCE, C_DB_SERVERTYPE, C_DB_NICENAME)
VALUES
('I2B2_DOMAIN_ID','SHRINE/','@','I2B2_DB_SHRINE_ONT_USER','java:/I2B2_DB_SHRINE_ONT_DATASOURCE_NAME','POSTGRESQL','SHRINE');

-- TODO: schema work for crc lookup?
insert into CRC_DB_LOOKUP
(C_DOMAIN_ID, C_PROJECT_PATH, C_OWNER_ID, C_DB_FULLSCHEMA, C_DB_DATASOURCE, C_DB_SERVERTYPE, C_DB_NICENAME)
VALUES
( 'I2B2_DOMAIN_ID', '/SHRINE/', '@', 'public', 'java:/I2B2_DB_CRC_DATASOURCE_NAME', 'POSTGRESQL', 'SHRINE' );


-- FILENAME:  ./skel/configure_pm.sql
-- Create user shrine/demouser
insert into PM_USER_DATA
(user_id, full_name, password, status_cd)
values
('SHRINE_USER', 'shrine', 'SHRINE_PASSWORD_CRYPTED', 'A');

-- TODO Override the ecommons requirement
-- http://open.med.harvard.edu/jira/browse/SHRINE-671
-- insert into PM_USER_PARAMS
-- (DATATYPE_CD, USER_ID, PARAM_NAME_CD, VALUE, CHANGEBY_CHAR, STATUS_CD)
-- values
-- ('T', 'shrine', 'ecommons_username', 'shrine', 'i2b2', 'A');

-- CREATE THE PROJECT for SHRINE
insert into PM_PROJECT_DATA
(project_id, project_name, project_wiki, project_path, status_cd)
values
('SHRINE', 'SHRINE', 'http://open.med.harvard.edu/display/SHRINE', '/SHRINE', 'A');

insert into PM_PROJECT_USER_ROLES
(PROJECT_ID, USER_ID, USER_ROLE_CD, STATUS_CD)
values
('SHRINE', 'SHRINE_USER', 'USER', 'A');

insert into PM_PROJECT_USER_ROLES
(PROJECT_ID, USER_ID, USER_ROLE_CD, STATUS_CD)
values
('SHRINE', 'SHRINE_USER', 'DATA_OBFSC', 'A');

-- captures information and registers the cells associated to the hive.
insert into PM_CELL_DATA
(cell_id, project_path, name, method_cd, url, can_override, status_cd)
values
('CRC', '/SHRINE', 'SHRINE Federated Query', 'REST', 'https://SHRINE_IP:SHRINE_SSL_PORT/shrine/rest/i2b2/', 1, 'A');


-- FILENAME:  ./skel/ontology_create_tables.sql
   -- modified to fit Postgres 2014-07-21

   -- I2b2 1.5 convention: Holds the SHRINE Ontology Table
   CREATE TABLE I2B2_DB_SHRINE_ONT_USER.SHRINE
   (
	C_HLEVEL NUMERIC(22,0),
	C_FULLNAME VARCHAR(900),
	C_NAME VARCHAR(2000),
	C_SYNONYM_CD CHAR(1),
	C_VISUALATTRIBUTES CHAR(3),
	C_TOTALNUM NUMERIC(22,0),
	C_BASECODE VARCHAR(450),
	C_METADATAXML TEXT,
	C_FACTTABLECOLUMN VARCHAR(50),
	C_TABLENAME VARCHAR(50),
	C_COLUMNNAME VARCHAR(50),
	C_COLUMNDATATYPE VARCHAR(50),
	C_OPERATOR VARCHAR(10),
	C_DIMCODE VARCHAR(900),
	C_COMMENT TEXT,
	C_TOOLTIP VARCHAR(900),
	UPDATE_DATE DATE,
	DOWNLOAD_DATE DATE,
	IMPORT_DATE DATE,
	SOURCESYSTEM_CD VARCHAR(50),
	VALUETYPE_CD VARCHAR(50),
        M_APPLIED_PATH VARCHAR(900),
        M_EXCLUSION_CD VARCHAR(900)
   ) ;
  ALTER TABLE I2B2_DB_SHRINE_ONT_USER.SHRINE OWNER TO I2B2_DB_SHRINE_ONT_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON I2B2_DB_SHRINE_ONT_USER.SHRINE TO I2B2_DB_ONT_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON I2B2_DB_SHRINE_ONT_USER.SHRINE TO I2B2_DB_SHRINE_ONT_USER;

-- I2b2 1.5 convention: Governs access to the SHRINE Ont table
  CREATE TABLE I2B2_DB_SHRINE_ONT_USER.TABLE_ACCESS
   (
    C_TABLE_CD VARCHAR(50),
	C_TABLE_NAME VARCHAR(50),
	C_PROTECTED_ACCESS CHAR(1),
	C_HLEVEL NUMERIC(22,0),
	C_FULLNAME VARCHAR(900),
	C_NAME VARCHAR(2000),
	C_SYNONYM_CD CHAR(1),
	C_VISUALATTRIBUTES CHAR(3),
	C_TOTALNUM NUMERIC(22,0),
	C_BASECODE VARCHAR(450),
	C_METADATAXML TEXT,
	C_FACTTABLECOLUMN VARCHAR(50),
	C_DIMTABLENAME VARCHAR(50),
	C_COLUMNNAME VARCHAR(50),
	C_COLUMNDATATYPE VARCHAR(50),
	C_OPERATOR VARCHAR(10),
	C_DIMCODE VARCHAR(900),
	C_COMMENT TEXT,
	C_TOOLTIP VARCHAR(900),
	C_ENTRY_DATE DATE,
	C_CHANGE_DATE DATE,
	C_STATUS_CD CHAR(1),
	VALUETYPE_CD VARCHAR(50)
   ) ;
  ALTER TABLE I2B2_DB_SHRINE_ONT_USER.TABLE_ACCESS OWNER TO I2B2_DB_SHRINE_ONT_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON I2B2_DB_SHRINE_ONT_USER.TABLE_ACCESS TO I2B2_DB_ONT_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON I2B2_DB_SHRINE_ONT_USER.TABLE_ACCESS TO I2B2_DB_SHRINE_ONT_USER;

   -- TODO: not sure how this is actually loaded up
   CREATE TABLE I2B2_DB_SHRINE_ONT_USER.SCHEMES
   (
    C_KEY VARCHAR(50) NOT NULL,
	C_NAME VARCHAR(50) NOT NULL,
	C_DESCRIPTION VARCHAR(100),
	 CONSTRAINT SCHEMES_PK PRIMARY KEY (C_KEY)
   )
   ;
  ALTER TABLE I2B2_DB_SHRINE_ONT_USER.SCHEMES OWNER TO I2B2_DB_SHRINE_ONT_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON I2B2_DB_SHRINE_ONT_USER.SCHEMES TO I2B2_DB_ONT_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON I2B2_DB_SHRINE_ONT_USER.SCHEMES TO I2B2_DB_SHRINE_ONT_USER;




-- FILENAME:  ./skel/ontology_create_user.sql
-- modified to fit Postgres 2014-07-23
create user I2B2_DB_SHRINE_ONT_USER with password 'I2B2_DB_SHRINE_ONT_PASSWORD';

-- create matching schema
create schema authorization I2B2_DB_SHRINE_ONT_USER;

-- i2b2metadata.table_access
grant all privileges on all tables in schema I2B2_DB_SHRINE_ONT_USER to I2B2_DB_SHRINE_ONT_USER;
grant all privileges on all sequences in schema I2B2_DB_SHRINE_ONT_USER to I2B2_DB_SHRINE_ONT_USER;
grant all privileges on all functions in schema I2B2_DB_SHRINE_ONT_USER to I2B2_DB_SHRINE_ONT_USER;


-- FILENAME:  ./skel/ontology_table_access.sql
-- modified to fit Postgres 2014-07-21

-- DELETE potential conflict entry from previous install, just to be safe.
delete from I2B2_DB_SHRINE_ONT_USER.TABLE_ACCESS where C_TABLE_CD = 'SHRINE';

-- Create a new entry in table access allowing this Ontology to be used for project SHRINE
INSERT into I2B2_DB_SHRINE_ONT_USER.TABLE_ACCESS
( C_TABLE_CD,
  C_TABLE_NAME,
  C_PROTECTED_ACCESS,
  C_HLEVEL,
  C_NAME,
  C_FULLNAME,
  C_SYNONYM_CD,
  C_VISUALATTRIBUTES,
  C_TOOLTIP,
  C_FACTTABLECOLUMN,
  C_DIMTABLENAME,
  C_COLUMNNAME,
  C_COLUMNDATATYPE,
  C_DIMCODE,
  C_OPERATOR)
values
( 'SHRINE',
  'SHRINE',
  'N',
   0,
   'SHRINE Ontology',
   '\SHRINE\',
   'N',
   'CA',
   'SHRINE Ontology',
   'concept_cd',
   'concept_dimension',
   'concept_path',
   'T',
   '\SHRINE\',
   'LIKE')
;
